name: Deploy to IONOS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Upload to IONOS via SCP
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.IONOS_HOST }}
          username: ${{ secrets.IONOS_USER }}
          password: ${{ secrets.IONOS_PASS }}
          port: ${{ secrets.IONOS_PORT }}
          source: "./"
          target: "/DesignWithReb"
